export {default as Ip} from './Ip/Ip'
export {default as Bidder } from './Bidder/Bidder'
export {default as Home } from './Home/Home'
export {default as Contact } from './Contact/Contact'
export {default as SearchResults } from './SearchResults/SearchResults'
export {default as Mybidding } from './Mybidding/Mybidding'
export {default as DataManagement } from './DataManagement/DataManagement'